const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function load(name,stubs={}) {const source=fs.readFileSync(__dirname+'/../force-app/main/default/lwc/'+name+'/'+name+'.js','utf8').replace(/^import .*;$/gm,'').replace(/^\s*@wire\(.*\)\s*$/gm,'').replace(/@(track|api)\s+/g,'').replace(/export default class \w+/,'globalThis.Component = class Component'); const c={LightningElement:class{dispatchEvent(){}},ShowToastEvent:class{},CustomEvent:class{},...stubs};vm.runInNewContext(source,c);return new c.Component();}
test('list shows draft cards and distinguishes unpublished changes from published cards',()=>{const b=load('cardstackFlowConfig');b.staging={liveValue:'[{"apiName":"Follow_Up","label":"Follow up"}]',draft:{Draft_Value__c:'[{"apiName":"Follow_Up","label":"Follow up"},{"apiName":"Review","label":"Review"}]'}};b.policies=JSON.parse(b.staging.draft.Draft_Value__c);b.search='';const rows=b.flowRows;assert.equal(rows.length,2);assert.equal(rows[0].status,'Published');assert.equal(rows[1].status,'Draft');b.search='review';assert.equal(b.flowRows.length,1);});
test('edit wizard keeps existing policy metadata and preserves other launch cards when staging',async()=>{let saved;const b=load('cardstackFlowWizard',{getStagingInfo:async()=>({liveValue:'[{"apiName":"Other","label":"Other"},{"apiName":"Review","label":"Old","inputs":[{"apiName":"recordId"}],"custom":"keep"}]'}),saveDraft:async x=>{saved=x;}});b.initialPolicy={apiName:'Review',label:'Old',inputs:[{apiName:'recordId'}],custom:'keep'};await b.loadExisting();b.flowLabel='New review';await b.stagePolicy();const policies=JSON.parse(saved.value);assert.equal(policies.length,2);assert.equal(policies[0].label,'Other');assert.equal(policies[1].label,'New review');assert.equal(policies[1].custom,'keep');assert.equal(policies[1].inputs[0].apiName,'recordId');assert.equal(policies[1].launchMode,'salesforce');});
test('going back to the flow picker preserves the custom chat label for the same flow',()=>{const b=load('cardstackFlowWizard');b.wiredFlowsResult={data:[{apiName:'Review',label:'Review flow',processType:'Flow'}]};b.handlePickFlow({currentTarget:{dataset:{apiname:'Review'}}});b.flowLabel='Approval review';b.ready=true;b.goToReview();assert.equal(b.step,2);b.goBack();assert.equal(b.step,1);b.handlePickFlow({currentTarget:{dataset:{apiname:'Review'}}});assert.equal(b.flowLabel,'Approval review');});
test('invalid saved policy data cannot silently overwrite existing configuration',async()=>{let saved=false;const b=load('cardstackFlowWizard',{getStagingInfo:async()=>({liveValue:'{broken'}),saveDraft:async()=>{saved=true;}});b.toast=()=>{};await b.loadExisting();b.selectedFlow={apiName:'Review',label:'Review'};b.flowLabel='Review';await b.stagePolicy();assert.equal(saved,false);});
test('changing the selected flow during edit does not copy the old flow input settings',async()=>{const b=load('cardstackFlowWizard',{getStagingInfo:async()=>({liveValue:'[{"apiName":"Review","label":"Review","inputs":[{"apiName":"reviewOnly"}]}]'})});b.initialPolicy={apiName:'Review',label:'Review',inputs:[{apiName:'reviewOnly'}]};await b.loadExisting();b.selectedFlow={apiName:'Different',label:'Different'};b.flowLabel='Different';const p=b.buildPolicy();assert.equal(p.apiName,'Different');assert.equal(p.inputs,undefined);});
test('Back from an existing-card edit closes the editor instead of changing its flow',async()=>{const b=load('cardstackFlowWizard',{getStagingInfo:async()=>({liveValue:'[{"apiName":"Review","label":"Review"}]'})});b.initialPolicy={apiName:'Review',label:'Review'};await b.loadExisting();let closed=false;b.done=()=>{closed=true;};b.goBack();assert.equal(closed,true);assert.equal(b.selectedFlow.apiName,'Review');});
test('a transient staging failure leaves the editor retryable and retry preserves the cards',async()=>{let calls=0;const b=load('cardstackFlowWizard',{getStagingInfo:async()=>({liveValue:'[{"apiName":"Review","label":"Review"}]'}),saveDraft:async()=>{if(++calls===1)throw new Error('Temporary save failure');}});b.initialPolicy={apiName:'Review',label:'Review'};await b.loadExisting();await b.stagePolicy();assert.equal(b.cannotStage,false);await b.stagePolicy();assert.equal(calls,2);});
